# EDA & Predictive Modeling of Chronic Illnesses

In [1]:
import pandas as pd

## Data Used

- **Dataset:** *[Chronic illness: symptoms, treatments and triggers](https://www.kaggle.com/datasets/flaredown/flaredown-autoimmune-symptom-tracker)* from Kaggle
    - **Download:** `export.csv (686.17 MB)`
- About the data:
    - **Size:** 7,976,223 rows x 9 cols
    - **Source:** *Flaredown* app, used for tracking chronic autoimmune and invisible illnesses
    - Includes conditions, symptoms, treatments, food, tags (“trackables”) recorded by users
    - Also includes weather, user info, and if applicable, HBI (Harvey Bradshaw Index), "a standardized metric to gauge the severity of Crohn's disease"

In [2]:
YOUR_DATA_PATH = 'data/export.csv'  # Set your path to the data

df = pd.read_csv(YOUR_DATA_PATH)
df.info()

/var/folders/7s/pcqsg24d2njdmmsp8w6d51qc0000gn/T/ipykernel_72882/762897023.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(YOUR_DATA_PATH)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7976223 entries, 0 to 7976222
Data columns (total 9 columns):
 #   Column           Dtype
---  ------           -----
 0   user_id          object
 1   age              float64
 2   sex              object
 3   country          object
 4   checkin_date     object
 5   trackable_id     object
 6   trackable_type   object
 7   trackable_name   object
 8   trackable_value  object
dtypes: float64(1), object(8)
memory usage: 547.7+ MB

In [3]:
df.shape

(7976223, 9)

In [4]:
df.head()

,user_id,age,sex,country,checkin_date,trackable_id,trackable_type,trackable_name,trackable_value
0,QEVuQwEABlEzkh7fsBBjEe26RyIVcg==,NaN,NaN,NaN,2015-11-26,1069,Condition,Ulcerative colitis,0
1,QEVuQwEAWRNGnuTRqXG2996KSkTIEw==,32.0,male,US,2015-11-26,1069,Condition,Ulcerative colitis,0
2,QEVuQwEA+WkNxtp/qkHvN2YmTBBDqg==,2.0,female,CA,2017-04-28,3168,Condition,pain in left upper arm felt like i was getting...,4
3,QEVuQwEA+WkNxtp/qkHvN2YmTBBDqg==,2.0,female,CA,2017-04-28,3169,Condition,hip pain when gettin up,3
4,QEVuQwEA+WkNxtp/qkHvN2YmTBBDqg==,2.0,female,CA,2017-04-28,3170,Condition,pain in hand joints,4

## EDA (Exploratory Data Analysis)

In [5]:
import plotly.express as px

### User Data

In [6]:
# Get User Data
print(f"Number of users: {len(df['user_id'].unique())}")
user_df = df[['user_id', 'age', 'sex', 'country']].copy()
user_df.drop_duplicates(inplace=True)
user_df

Number of users: 42283

                                  user_id   age         sex country
0        QEVuQwEABlEzkh7fsBBjEe26RyIVcg==   NaN         NaN     NaN
1        QEVuQwEAWRNGnuTRqXG2996KSkTIEw==  32.0        male      US
2        QEVuQwEA+WkNxtp/qkHvN2YmTBBDqg==   2.0      female      CA
22       QEVuQwEAHgM/igE3w0tBL14Jq1nEfw==   NaN         NaN     NaN
23       QEVuQwEAO+R1md5HUn8+w1Qpbg7ogw==   NaN         NaN     NaN
...                                   ...   ...         ...     ...
7970576  QEVuQwEAs8PnkVUj+4SbIE/3Eh4vSg==  30.0       other      US
7974772  QEVuQwEAvkCVm+/1EeCVt4W69d+JAw==  35.0  doesnt_say      US
7975104  QEVuQwEAe+Me/lpz+GEjbH7bMu3UeA==  38.0      female      JP
7975409  QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==  48.0        male      GB
7976206  QEVuQwEAtlfm8VyoxZ9biWjDHb74gQ==  22.0      female      GB

[42283 rows x 4 columns]

#### User Counts by Sex

In [7]:
# Plot User Counts by Sex
fig = px.histogram(user_df, x='sex', title='User Counts by Sex')
fig.show()

- The vast majority of users (82%) are female

#### Top 10 Countries by User Counts

In [68]:
# Get Top 10 countries df
country_df = user_df.groupby('country').count()['user_id'].reset_index()
country_df['count'] = country_df['user_id']
country_df = country_df.sort_values('count', ascending=False)[:10]
# Plot Top 10 Countries by User Counts
fig = px.pie(country_df, values='count', names='country', 
             title='Top 10 Countries by User Counts',
             )
fig.show()

- Top countries are: US, followed by Great Britain, Canada, Australia, then New Zealand and others

#### User Counts by Age

In [9]:
df['age'].value_counts()

age
 28.0       287806
 39.0       286534
 29.0       276379
 32.0       273345
 33.0       260734
             ...
 85.0            3
-19963.0         3
 361.0           1
-33.0            1
 86.0            1
Name: count, Length: 100, dtype: int64

In [10]:
# Get invalid ages data
user_df.loc[(df['age'] > 100) | (df['age'] <= 0)]

                                  user_id       age         sex country
598      QEVuQwEAZOJ2BbfmaLgCwhLQzwdKag==     118.0  doesnt_say      AU
43808    QEVuQwEAL0wmX+OCpgHS+d3F3ftvgg==     -43.0      female      US
122569   QEVuQwEAOErHMawDAupXZB/KaEQhpQ==       0.0      female      IN
122725   QEVuQwEAOGcYXmDK5KzGxru6bqgxRQ==  -19963.0  doesnt_say      IL
179433   QEVuQwEAYeEPxvaUylfHEwXUgr3T9g== -196691.0        male      CA
203023   QEVuQwEA53bmvFhv/THxsqJHWATqog==    1942.0      female      CA
313550   QEVuQwEAvq1rRfTTtLtUQ42yOQv0PQ==     -33.0      female      GB
647435   QEVuQwEAiLMCOYKtoAunyLpqZ8g7iw==    2018.0  doesnt_say      US
739914   QEVuQwEAavl59D+XLfYhf32PkYHYhg==     219.0      female      GB
817993   QEVuQwEAkC/MlrDnguep3Z76MJrCdg==     829.0      female      US
941805   QEVuQwEA/qP3J+jua5eAnFItIpBjyg==       0.0        male      NG
970128   QEVuQwEAkXq09U0UnrwzN96BMwp0lA==     785.0  doesnt_say      US
1161871  QEVuQwEA2TKGY3hHlLe/DwfK0Fnucg==       0.0      female      US
1329897  QEVuQwEAUVnI73tmGEm2qi3k27mi4w==     361.0      female      US
7269634  QEVuQwEA9KFnubyv4AUUfbKOXi/iag==     -30.0  doesnt_say      US

- There are invalid ages (> 100 or <= 0), so let's remove them.

In [11]:
# Keep only valid ages
valid_age_user_df = user_df.loc[(user_df['age'] <= 100) 
                                & (user_df['age'] > 0)].copy()
print(f"Number of users: {len(valid_age_user_df['user_id'].unique())}")
# Plot User Counts by Age
fig = px.histogram(valid_age_user_df, x='age', nbins=20, 
                   title='User Counts by Age')
fig.show()

Number of users: 40589

- Most users (7,475 or 18%) are 25-29
- There are a good amount of users (380) aged 0-4
    - Perhaps these users are parents tracking their baby's health

### Check-In Counts by Month

In [13]:
import datetime

In [ ]:
# Get user check-in dates df
checkin_df = df[['user_id', 'checkin_date']].drop_duplicates()
checkin_df['checkin_date'] = pd.to_datetime(checkin_df['checkin_date'])
checkin_df = checkin_df.set_index('checkin_date')
checkin_df

                                       user_id
checkin_date
2015-11-26    QEVuQwEABlEzkh7fsBBjEe26RyIVcg==
2015-11-26    QEVuQwEAWRNGnuTRqXG2996KSkTIEw==
2017-04-28    QEVuQwEA+WkNxtp/qkHvN2YmTBBDqg==
2015-06-22    QEVuQwEAHgM/igE3w0tBL14Jq1nEfw==
2015-05-26    QEVuQwEAO+R1md5HUn8+w1Qpbg7ogw==
...                                        ...
2019-10-13    QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==
2019-10-21    QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==
2019-12-04    QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==
2019-12-03    QEVuQwEA/3ZnJPHdtLiOWBy1VAYIYA==
2019-12-04    QEVuQwEAtlfm8VyoxZ9biWjDHb74gQ==

[383228 rows x 1 columns]

In [35]:
# Get monthly check-in counts
monthly_checkin_df = checkin_df.resample('ME').count()
monthly_checkin_df['count'] = monthly_checkin_df['user_id']
monthly_checkin_df = monthly_checkin_df.reset_index()
monthly_checkin_df
# Plot Check-In Counts by Month
fig = px.line(monthly_checkin_df, x='checkin_date', y='count', title='Check-In Counts by Month')
fig.show()

- The highest number of check-ins occurred in Jan 2019
    - This may be due to excitement for the new year and New Year's resolutions
- There is a dropoff in check-in counts in Dec 2019
    - This may be due to the dataset ending with only partial data for the final month

### Trackables

#### Trackable Types

In [69]:
# Get Trackable Types df
trackable_types_df = df.groupby('trackable_type').count()['user_id'].reset_index()
trackable_types_df['count'] = trackable_types_df['user_id']
trackable_types_df = trackable_types_df.sort_values('count', ascending=False)
# Plot Trackable Types Breakdown
fig = px.pie(trackable_types_df, values='count', names='trackable_type', 
             title='Trackable Types Breakdown',
             )
fig.show()

- Top trackable types are: Symptom, followed by Weather, Condition, Treatment, Food,  then Tag and HBI

#### Trackable Names

In [61]:
# Get Top 10 Trackable names df
trackable_names_df = df.groupby(['trackable_type', 'trackable_name']).count()['user_id'].reset_index()
trackable_names_df['count'] = trackable_names_df['user_id']
trackable_names_df = trackable_names_df.sort_values('count', ascending=False)
trackable_names_df

       trackable_type                 trackable_name  user_id   count
121353        Weather                temperature_min   232301  232301
121352        Weather                temperature_max   232301  232301
121351        Weather                       pressure   232301  232301
121350        Weather               precip_intensity   232301  232301
121349        Weather                           icon   232301  232301
...               ...                            ...      ...     ...
49658            Food                 spaggeti hoops        1       1
49656            Food                     spagettios        1       1
49654            Food  spagetti squash with marinara        1       1
49653            Food                spagetti squash        1       1
0           Condition                    Aching legs        1       1

[121354 rows x 4 columns]

- Let's drop Weather trackables, which are pulled via API and not user input

In [64]:
trackable_names_df = trackable_names_df.drop(trackable_names_df.loc[trackable_names_df['trackable_type']=='Weather'].index)
trackable_names_df = trackable_names_df.sort_values('count', ascending=False)[:15]
trackable_names_df

       trackable_type         trackable_name  user_id   count
59260         Symptom               Headache   108550  108550
58407         Symptom                Fatigue   107512  107512
61309         Symptom                 Nausea    89520   89520
56807         Symptom              Brain fog    73175   73175
60088         Symptom             Joint pain    64936   64936
58423         Symptom  Fatigue and tiredness    63395   63395
56242         Symptom                Anxiety    61545   61545
109379            Tag                  tired    57084   57084
1460        Condition           Fibromyalgia    55255   55255
57563         Symptom               Diarrhea    52418   52418
57735         Symptom              Dizziness    50150   50150
1026        Condition             Depression    50109   50109
201         Condition                Anxiety    46968   46968
57526         Symptom             Depression    43370   43370
57300         Symptom           Constipation    40874   40874

In [70]:
# Plot Top 15 Trackable Names Breakdown
fig = px.pie(trackable_names_df, values='count', names='trackable_name', 
             title='Top 15 Trackable Names Breakdown',
             )
fig.show()

- The top trackable names are: Headache, followed by Anxiety, Fatigue, Depression, and then Nausea and others

## Data Preprocessing

## Predictive Modeling